name: XML Processor Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo ::set-output name=dir::$(composer config cache-files-dir)

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run test suite
        run: composer run-script test

      - name: Install Phar tools and build deployment artefact.
        run: |
          composer phar:install-tools
          rm -rf vendor/*
          composer install --prefer-dist --no-dev --no-interaction --no-progress
          composer phar:build

      - name: Run the phar
        run: |
          export XML_PROCESSOR_LOG_LOCATION="./app.log"
          export XML_PROCESSOR_API_CREDENTIALS="tests/File/creds.json"
          php xml-processor.phar  --version
          unset XML_PROCESSOR_LOG_LOCATION
          unset XML_PROCESSOR_API_CREDENTIALS

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-php-${{ matrix.php-versions }}-xml-processor.phar
          path: xml-processor.phar
          if-no-files-found: error
