name: XML Processor Test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        php-versions: ['8.1']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      - name: Run test suite
        run: composer run-script test

      - name: Install Phar tools and build deployment artefact.
        run: |
          composer phar:install-tools
          rm -rf vendor/*
          composer install --prefer-dist --no-dev --no-interaction
          composer phar:build

      - name: Run the phar
        run: php xml-processor.phar

      - name: Upload artefact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-php-${{ matrix.php-versions }}-xml-processor.phar
          path: xml-processor.phar
          if-no-files-found: error
